import math
import pygame

pygame.font.init()

BACKGROUND_BOARD = (255, 255, 255)
BACKGROUND_PANEL = (100, 100, 100)
HIGHLIGHT_BOARD = (170, 170, 170)

BLACK = (0, 0, 0)

SIZE = 1200, 800
WIDTH, HEIGHT = SIZE

PANEL_LOCATION = (HEIGHT, 0)
PANEL_WIDTH = WIDTH - HEIGHT
PANEL_SIZE = (PANEL_WIDTH, HEIGHT)

PANEL = pygame.Rect(PANEL_LOCATION, PANEL_SIZE)
FONT = "couriernew"

FONT_RATIOS = {"couriernew": 0.6}

SQUARE_WIDTH = int(HEIGHT / 13)

PIECE_PADDING = int(math.ceil(3 * SQUARE_WIDTH / 100))
SYMBOL_PADDING = int(math.ceil(28 * SQUARE_WIDTH / 100))

PIECE_SIZE = int(94 * SQUARE_WIDTH / 100)
SYMBOL_SIZE = int(44 * SQUARE_WIDTH / 100)

BARRIER_SIZE = int(92 * SQUARE_WIDTH / 100)
BARRIER_PADDING = int(math.ceil(4 * SQUARE_WIDTH / 100))

BUTTON_COLOUR = (170, 170, 170)
BUTTON_HIGHLIGHT_COLOUR = (200, 200, 200)

BUTTON_FONT = pygame.font.SysFont(FONT, 20, bold=True)
BUTTON_TEXT_COLOUR = BLACK


PIECE_BUTTON_WIDTH = int(HEIGHT / 6)

PIECE_BUTTON_HEIGHT = int(HEIGHT / 25)

CONDITION_SIZE = int(math.ceil(SQUARE_WIDTH / 5))